apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    fdk.service: registration-auth
  name: registration-auth
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: registration-auth
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ required "Missing value FDK_REGISTRATION_AUTH_SPRING_PROFILES_ACTIVE" .Values.FDK_REGISTRATION_AUTH_SPRING_PROFILES_ACTIVE }}
        image: {{ required "Missing value REGISTRATION_AUTH_IMAGE" .Values.REGISTRATION_AUTH_IMAGE }}
        imagePullPolicy: Always
        name: registration-auth
        ports:
        - containerPort: 8080
        resources: 
          requests:
            memory: {{ required "Missing value FDK_REGISTRATION_AUTH_MEMORY" .Values.FDK_REGISTRATION_AUTH_MEMORY | quote }}
      restartPolicy: Always
status: {}
