logging:
  level.: ERROR
  level.no.brreg: INFO
  level.no.difi: ERROR
  level.no.dcat: INFO
  level.org.springframework: ERROR
  level.org.springframework.web: ERROR
spring:
  mvc.view.prefix: /WEB-INF/jsp/
  mvc.view.suffix: .jsp
server:
  port: 8080
management:
  server:
    port: 8181
fuseki:
  dcatServiceUri: ${fusekiDcatServiceUri:http://fuseki:8080/fuseki/dcat}
  adminServiceUri: ${fusekiAdminServiceUri:http://fuseki:8080/fuseki/admin}
application:
  harvesterUrl: ${harvesterUrl:http://harvester-api:8080}
  adminUsername: ${harvester_adminUsername}
  adminPassword: ${harvester_adminPassword}

---
spring:
  profiles: develop
fuseki:
  dcatServiceUri: http://localhost:3030/fuseki/dcat
  adminServiceUri: http://localhost:3030/fuseki/admin
application:
  harvesterUrl: http://localhost:8081
server:
  port: 8082
management:
  server:
    port: 8992
