logging:
  level.: ERROR
  level.no.brreg: ERROR
  level.no.difi: INFO
  level.no.dcat: INFO
  level.org.springframework: ERROR
  level.org.springframework.web: ERROR
  level.org.elasticsearch: WARN
server:
  port: 8080
management:
  server:
    port: 8181
application:
  httpUsername: ${themesHttpUsername:user}
  httpPassword: ${themesHttpPassword:password}
  referenceDataUrl: ${referenceDataUrl:http://reference-data:8080}
  notificationMailSenderAddress: fdksystembjg@gmail.com
  openDataEnhet: https://data.brreg.no/enhetsregisteret/api/enheter/
crawler:
  threadPoolSize: 2
elastic:
  clusterNodes: ${FDK_ES_CLUSTERNODES:elasticsearch:9300}
  clusterName: ${FDK_ES_CLUSTERNAME:elasticsearch}
fuseki:
  dcatServiceUri: ${fusekiDcatServiceUri:http://fuseki:8080/fuseki/dcat}
  adminServiceUri: ${fusekiAdminServiceUri:http://fuseki:8080/fuseki/admin}

---
spring:
  profiles: prod
  mail:
    host: smtprelay.brreg.no
application:
  notificationMailSenderAddress: ${emailSenderAddress}

---
spring:
  profiles: develop, unit-integration
  mail:
    host: smtp.gmail.com
    port: 587
    username: fdksystembjg
    password: xxxx
    properties:
      mail:
        smtp:
          auth: true
          connectionTimeout: 5000
          timeout: 3000
          writetimeout: 5000
          starttls:
            enable: true

fuseki:
  dcatServiceUri: http://localhost:3030/fuseki/dcat
  adminServiceUri: http://localhost:3030/fuseki/admin
application:
  referenceDataUrl: http://localhost:8100
  notificationMailSenderAddress: fdksystembjg@gmail.com

elastic:
  clusterNodes: localhost:9300
  clusterName: elasticsearch
server:
  port: 8081
management:
  server:
    port: 8991

---
spring:
  profiles: docker
  mail:
    host: smtp.gmail.com
    port: 587
    username: fdksystembjg
    password: xxxx
    properties:
      mail:
        smtp:
          auth: true
          connectionTimeout: 5000
          timeout: 3000
          writetimeout: 5000
          starttls:
            enable: true
application:
  notificationMailSenderAddress: fdksystembjg@gmail.com
