logging:
  level.: ERROR
  level.no.brreg: ERROR
  level.no.difi: ERROR
  level.no.dcat: INFO
  level.org.springframework: ERROR
server:
  port: 8080
management:
  server:
    port: 8181
application:
  fusekiHost: http://fuseki:8080
  harvesterHost: http://harvester-api:8080
elastic:
  clusterNodes: ${FDK_ES_CLUSTERNODES:elasticsearch:9300}
  clusterName: ${FDK_ES_CLUSTERNAME:elasticsearch}

---
#Utv-miljø lokalt på egen PC
spring:
  profiles: develop
application:
  fusekiHost: http://localhost:3030
  harvesterHost: http://localhost:8081
elastic:
  clusterNodes: localhost:9300
  clusterName: elasticsearch
server:
  port: 8074
management:
  server:
    port: 8994